Update git submodules
* Update frameworks/support from branch 'androidx-main'
  to 61d63a1aed7849a8d55f91446d578162ed43e2e4
  - Merge "Gate lastResourceOnlyWatchFacePackageName with a latch" into androidx-main
  - Gate lastResourceOnlyWatchFacePackageName with a latch
    
    This should ensure the test doesn't fail due to
    kotlin.UninitializedPropertyAccessException: lateinit property
    lastResourceOnlyWatchFacePackageName has not been initialized.
    
    Test: Presubmit
    Bug: 290179105
    Change-Id: I30853cf8b688eb91c3c4fdb90413c708f4a6488b