Update git submodules
* Update frameworks/support from branch 'androidx-main'
  to c587aa25f503ab8cb2f2632529768f96b3a310ee
  - Merge "build_log_simplifier now shortening all non-androidx stackframes" into androidx-main
  - build_log_simplifier now shortening all non-androidx stackframes
    
    They're not usually very helpful to us.
    Occasionally they are helpful, though (for example Dackka index out of bounds errors b/199393040) so we still add "..." at the end to remind users that there are more stack frames in build.log
    
    Bug: 330373483
    
    Test: Run `/google/data/ro/projects/android/fetch_artifact --bid 11614496 --target androidx_with_metalava 'logs/gradle.log' && \
          ./development/build_log_simplifier.py gradle.log`
          # and see that it says this:
    
            Detected these failing tasks: []
            Calculating task graph as configuration cache cannot be reused because the file system entry '../../out/androidx/compose/material/material-icons-core/build/generatedIcons/allVariants/src/commonMain/kotlin' has been created.
            > Task :wear:compose:compose-navigation:checkApi UP-TO-DATE
    
            java.io.FileNotFoundException: $OUT_DIR/androidx/build/TaskUpToDateValidator/listTaskOutputs/up-to-date/outputs (No such file or directory)
            > $OUT_DIR/androidx/build/TaskUpToDateValidator/listTaskOutputs/up-to-date/outputs (No such file or directory)
    
            * Exception is:
            org.gradle.api.UncheckedIOException: java.io.FileNotFoundException: $OUT_DIR/androidx/build/TaskUpToDateValidator/listTaskOutputs/up-to-date/outputs (No such file or directory)
            	at jdk.proxy1/jdk.proxy1.$Proxy39.buildFinished(Unknown Source)...
            Caused by: java.io.FileNotFoundException: $OUT_DIR/androidx/build/TaskUpToDateValidator/listTaskOutputs/up-to-date/outputs (No such file or directory)
            	at kotlin.io.FilesKt__FileReadWriteKt.forEachLine(FileReadWrite.kt:190)...
            	at androidx.build.uptodatedness.TaskUpToDateValidator$Companion.loadTaskOutputs(TaskUpToDateValidator.kt:381)
            	at androidx.build.uptodatedness.TaskUpToDateValidator$Companion.access$loadTaskOutputs(TaskUpToDateValidator.kt:277)
            	at androidx.build.uptodatedness.TaskUpToDateValidator.tryToExplainTaskExecution(TaskUpToDateValidator.kt:241)
            	at androidx.build.uptodatedness.TaskUpToDateValidator.onFinish(TaskUpToDateValidator.kt:205)
    
            BUILD FAILED in 1m 23s
    
    Change-Id: Ia6878ac7639c64c1d68c75d4ebdb196ba618904f