Update git submodules
* Update frameworks/support from branch 'androidx-main'
  to b31cdf98bf9fc59d69a3dacd4452edfe88e9fd02
  - Merge "Disable RoomDriverBenchmark" into androidx-main
  - Disable RoomDriverBenchmark
    
    Currently broken due to:
    
    kotlin.UninitializedPropertyAccessException: lateinit property database has not been initialized
    	at androidx.room.benchmark.RoomDriverBenchmark.cleanup(RoomDriverBenchmark.kt:81)
    
    Test: RoomDriverBenchmark
    Change-Id: Iea3b5de82c34e06f0e4441cd8ad66524047acc21