metalava: Fail instead of generating broken stubs for methods from hidden superclasses
Fixes an issue where public methods inherited generic superclasses
might have a stub whose bytecode signature does not match the runtime
signature in the hidden superclass, leading to a NoSuchMethodError
at runtime.

Instead of generating a bogus stub, metalava now fails when a generic
method cannot be pushed down without altering its erased signature.

Fixes: 182906753
Bug: 182906753
Test: ./gradlew test --tests ApiAnalyzerTest
Change-Id: I8bd0984fe491ddcc7776741469df4baea08bbe8c