Update git submodules
* Update frameworks/support from branch 'androidx-main'
  to 42c5417ed12e2a5d70541afa1ee8b53cf489a9a6
  - Merge changes I9612558b,I4682e522,I16164061,I8e55f866,I6d4e9504, ... into androidx-main
    
    * changes:
      Configuration caching fix for CheckExternalDependencyLicensesTask
      fix car:app:app configuration caching
      fix in compose:desktop:desktop for configuration caching of project.group
      AndroidXDocsImplPlugin fix for configuration caching
      CreateLibraryBuildInfoFileTask more fixes for configuration caching
      configuration caching fix for ComposeImplPlugin.enableMetrics
    
  - Configuration caching fix for CheckExternalDependencyLicensesTask
    
    Bug: 180423646
    Test: enable configuration caching and run `./gradlew checkExternalLicenses -Pandroidx.verifyUpToDate`
    Test: enable configuration caching and run `find ../../prebuilts/androidx/external -name "LICENSE*" | xargs rm -f; ./gradlew checkExternalLicenses` # and see that it notices that the licence files are missing
    
    Change-Id: I9612558bcf0b10f849f9f792d7f8b15fb113aab0
    
  - fix car:app:app configuration caching
    
    Bug: 180423646
    
    Test: enable configuration caching, run busytown/androidx.sh, and that there is no longer an error in :car:app:app:generateProtocolApi saying:
    
      Extension of type 'LibraryExtension' does not exist.
    
    Change-Id: I4682e522baabb01c53619aa1b6144f0da826657a
    
  - fix in compose:desktop:desktop for configuration caching of project.group
    
    Bug: 180423646
    Test: enable configuration caching and run busytown/androidx_multiplatform.sh and see that it doesn't emit this error:
    
      groovy.lang.MissingPropertyException: Could not get unknown property 'group' for [contents of the pom file here]
    
    Change-Id: I161640616796705404862ddf33429a4e6978e298
    
  - AndroidXDocsImplPlugin fix for configuration caching
    
    Bug: 180423646
    
    Test: enable configuration caching and run busytown/androidx.sh and see that it no longer emits this error:
    
      org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':docs-tip-of-tree:unzipSampleSources'.
      Caused by: kotlin.UninitializedPropertyAccessException: lateinit property project has not been initialized
      	at androidx.build.docs.AndroidXDocsImplPlugin.getProject(AndroidXDocsImplPlugin.kt:71)
      	at androidx.build.docs.AndroidXDocsImplPlugin$configureUnzipTask$1$1.transform(AndroidXDocsImplPlugin.kt:166)
      	at androidx.build.docs.AndroidXDocsImplPlugin$configureUnzipTask$1$1.transform(AndroidXDocsImplPlugin.kt:164)
    
    Change-Id: I8e55f866c8f2b7ced656c32b30eab658d9f33fc8
    
  - CreateLibraryBuildInfoFileTask more fixes for configuration caching
    
    It's still not down to zero problems but it's closer
    
    Bug: 180423646
    Test: enable configuration caching and run `./gradlew createLibraryBuildInfoFiles` and see that there are only 298 problems
    Change-Id: I6d4e95045590d209ad3ef64b10786d77fd2234e8
    
  - configuration caching fix for ComposeImplPlugin.enableMetrics
    
    Bug: 180423646
    Test: enable configuration caching, run bustown/androidx_host_tests.sh, and see that there are fewer problems (fewer uses of `project` during task execution, which becomes unsupported when configuration caching is enabled)
    
    Change-Id: I3fa34d573cf08f7e6e0af74fc76928b402b3dc83