Update git submodules
* Update frameworks/support from branch 'androidx-main'
  to 8bb7a9868d01368a9d5f3103f06de57528881330
  - Merge "Replace mockito in RecorderTest tests with NoClassDefFoundError" into androidx-main
  - Replace mockito in RecorderTest tests with NoClassDefFoundError
    
    Also refactored code of aosp/2259811
    
    Some tests are failing due to a dexmaker issue of older mockito version
    and updating mockito to latest version causes different problem.
    Also, mockito is no longer recommended for androidx, so mockito usage is being
    removed from these tests and they are being tested manually while keeping the behavior same.
    
    Bug: b/239752223
    Test: ./gradlew bOS
    
    Signed-off-by: Tahsin Masrur <tahsinm@google.com>
    Change-Id: I5d46074b214db94a40b9d16757e6549772ffd7a6