Update git submodules
* Update frameworks/support from branch 'androidx-main'
  to 2414f57d38136a22798dbba142a420cdd840a306
  - Merge "[GH] Fix ComposableNamingDetector crash on internal functions" into androidx-main
  - [GH] Fix ComposableNamingDetector crash on internal functions
    
    `Composable`s with internal modifiers inside a class/interface/object will crash the `ComposableNamingDetector`.
    
    ```kotlin
    object Foo {
        @Composable
        internal fun Content(): @Composable () -> Unit = {}
    }
    ```
    
    The computed `UMethod#name` for this will be `Content$impl`, which is then used in the `LintFix` to replace a String that does not exist in the source code. Leading to this crash:
    
    ```
    Couldn't compute fix edits for Change to content$impl
    java.lang.IllegalArgumentException: Did not find "Content$impl" in "Content" in [...]
    Consider calling ReplaceStringBuilder#range() to set a larger range to search than the default highlight range.
    ```
    
    ## Proposed Changes
    
    Use `UElement#nameFromSource` instead
    
    ## Testing
    
    Test: added a `nestedAndInternalModifierIsSupported()` test case
    
    ## Issues Fixed
    
    Issue: https://issuetracker.google.com/issues/461736991
    
    This is an imported pull request from https://github.com/androidx/androidx/pull/828.
    
    Resolves #828
    Github-Pr-Head-Sha: 34eaedc5a1a8e8d2de87a7dadaf1f084c5769490
    GitOrigin-RevId: 6b59b1a865daea1ac794e6f06bed2b0a5ae34f79
    Change-Id: I617f6de7e5991c13323b6d7085306305c3f5563a