Update git submodules
* Update frameworks/support from branch 'androidx-main'
  to 5cfb15f8a692f7b9130c1412d902ed306ad0af59
  - Merge "Fixes EditTextPreferenceDialogFragmentCompatTest on older devices" into androidx-main
  - Fixes EditTextPreferenceDialogFragmentCompatTest on older devices
    
    BooleanSupplier isn't always available, which causes a java.lang.NoClassDefFoundError: java/util/function/BooleanSupplier
    
    Fixes: b/190194402
    Test: EditTextPreferenceDialogFragmentCompatTest
    Change-Id: I30fa3607c0241de7b4391e72fcfdba20bf678ba9