Update git submodules
* Update frameworks/support from branch 'androidx-main'
  to 7da7cc114c52631d781937925e679e913f85c407
  - Merge "Revert "Bump androidx.test.core to 1.4.0"" into androidx-main
  - Revert "Bump androidx.test.core to 1.4.0"
    
    This reverts commit 90402bb1a78f6962bc095d01d667ece5356cc8dd.
    
    Reason for revert: Broke a number of @LargeTest across the codebase.
    Example https://android-build.googleplex.com/builds/tests/view?invocationId=I63900009972892409
    
    It seems to be missing some of upgrades to 1.4.0
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/test/internal/platform/app/ActivityInvoker$-CC;
    
    Change-Id: Ia36bd5712921fa081fcba16886aa148a76cff20d