Update git submodules
* Update frameworks/support from branch 'androidx-main'
  to 26d664b327e9526c2146afa0d0bf08137dcf234a
  - Merge "Partially revert "Close test database in all WorkManager tests"" into androidx-main
  - Partially revert "Close test database in all WorkManager tests"
    
    This reverts commit ffbc863a436d7ddf847cb5216a82fd0af1cad3b0.
    
    Reason for revert: LazyColumn tests started flaking with error "Cannot perform this operation because the connection pool has been closed.
    java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed."
    
    Change-Id: Ib2f4dac3ce579cc96de69fda59c104590e6ef02c