Update git submodules
* Update frameworks/support from branch 'androidx-main'
  to 8ed44662e452805ee7a783dcf0e5f2dea741b47a
  - Merge "Fix AdvancedExtenderValidationTest test failures caused by NoClassDefFoundError" into androidx-main
  - Fix AdvancedExtenderValidationTest test failures caused by NoClassDefFoundError
    
    This issue won't happen when connecting to the lab devices remotely and
    running the test. This issue might be caused by the build environment
    when running the test via MobileHarness system. I explicitly override
    the methods to return the default values to avoid the issue.
    
    Bug: 441609756
    Test: AdvancedExtenderValidationTest
    Change-Id: Iac84171dd28dfd722e110eb61c06b47c9ef9a6f9