Update git submodules
* Update frameworks/support from branch 'androidx-main'
  to cde689f27f1e678a1862270ade5affe3e2f75b0b
  - Merge "Set persist.traced.enable, and add clearer perfetto errors" into androidx-main
  - Set persist.traced.enable, and add clearer perfetto errors
    
    Test: ./gradlew bench:b-m:cC bench:b-m-j:cC
    Test: ProcessSpeedProfileValidation #(with false error, output below)
    Test: StartupTimingMetricTest # after setprop persist.traced.enable 0
    Bug: 180956594
    Fixes: 181260845
    
    Use persist.traced.enable on devices that require it to enable
    perfetto capture.
    
    Print device info in suspected device-specific exceptions, make
    perfetto start errors granular, and print trace files to provide in
    bugreport if metrics are missing.
    
    Additionally, add brand to context json output, for consistency with
    device info logging.
    
    Sample failure 1:
    
    ```
    java.lang.IllegalStateException: Perfetto tracing failed to start. Command output = 31875
    
    Please report a bug, and include a logcat capture of the test run and failure.DeviceInfo(Brand=google, Model=Pixel 2, SDK=30, BuildFp=google/walleye/walleye:11/RP1A.201005.004.A1/6934943:user/release-keys)
    ```
    
    Sample failure 2:
    ```
    java.lang.IllegalStateException: Error, different metrics observed in different iterations.
    
    Please report a bug, and include a logcat capture, and all traces captured by this test run:
    /storage/emulated/0/Android/data/androidx.benchmark.integration.macrobenchmark.test/cache/ProcessSpeedProfileValidation_start[compilation_mode=androidx.benchmark.macro.CompilationMode.None,startup_mode=WARM]_iter000.trace
    /storage/emulated/0/Android/data/androidx.benchmark.integration.macrobenchmark.test/cache/ProcessSpeedProfileValidation_start[compilation_mode=androidx.benchmark.macro.CompilationMode.None,startup_mode=WARM]_iter001.trace
    /storage/emulated/0/Android/data/androidx.benchmark.integration.macrobenchmark.test/cache/ProcessSpeedProfileValidation_start[compilation_mode=androidx.benchmark.macro.CompilationMode.None,startup_mode=WARM]_iter002.trace
    DeviceInfo(Brand=google, Model=Pixel 2, SDK=30, BuildFp=google/walleye/walleye:11/RP1A.201005.004.A1/6934943:user/release-keys)
    	at androidx.benchmark.macro.MetricResultExtensionsKt.mergeToMetricResults(MetricResultExtensions.kt:36)
    ```
    
    Change-Id: Ic5d01dceb67abc4ea4f0e8e5057a38fee93c03c0