Update git submodules
* Update frameworks/support from branch 'androidx-main'
  to 9e9be6b0b7affded039b42272bd91b8220b5b176
  - Merge "Fix Compose Desktop build with Kotlin 1.4.* and Gradle 7" into androidx-main
  - Fix Compose Desktop build with Kotlin 1.4.* and Gradle 7
    
    Currently, Androidx project uses Gradle 7 and Kotlin 1.4.32
    There are some incompatibilities between the two, which only
    affect multiplatform build of Compose Desktop.
    
    There are two issues breaking Compose Desktop build:
    1. https://youtrack.jetbrains.com/issue/KT-46096
       Gradle 7 removed 'compile' and 'runtime'
       configurations, which were referred in
       `KotlinJvmTarget.withJava` method, leading
       to the NoSuchMethodError.
       Only `:compose:desktop:desktop` module is affected.
       The module does not contain Java code, but `withJava`
       is necessary for configuring publishing correctly.
    
       This change adds a workaround by copying the fixed
       `withJava` implementation from Kotlin 1.5.
       The change affects only `:compose:desktop:desktop`,
       which is configured only with the property
       `-Pandroidx.compose.multiplatformEnabled=true`.
    
    2. https://youtrack.jetbrains.com/issue/KT-46165
       Gradle 7 started to throw an exception on duplicate
       entry, when `Jar.duplicateStrategy` is not set.
       This affects `*SourcesJar` task of Android MPP source sets
       only when Multiplatform plugin is used.
    
       This change works around the issue by setting
       `duplicatesStrategy` to `INCLUDE`, but only when
       multiplatform build is enabled and only for subprojects,
       that use the Kotlin multiplatform plugin.
    
    Both workarounds do not affect the build when
    `androidx.compose.multiplatformEnabled` is set to `false`,
    which is the default, so they should not affect
    Android Compose builds in any way.
    The changes are proposed as a temporary workarounds,
    until Kotlin 1.5 is used to build Compose.
    Once it happens, this commit will be reverted.
    
    Test: tested multiplatform publishing manually.
    Non multiplatform builds are not affected.
    
    Signed-off-by: Alexey Tsvetkov <alexey.tsvetkov@jetbrains.com>
    Change-Id: I2783b4ee833357dfaa14ccd93ae2b0cef6a0bde6