Update git submodules
* Update frameworks/support from branch 'androidx-main'
  to 891b6e4d7f9d5ce214dd4babf04910b251ed4c71
  - Merge "[GH] Fix paging playground" into androidx-main
  - [GH] Fix paging playground
    
    Different version of annotations was being pulled in for the integration test app vs its instrumented tests, which was causing them to fail to build with:
    
    GradleException: Cannot find a version of 'androidx.annotation:annotation' that satisfies the version constraints:...
    
    Test: cd paging && ./gradlew bOS
    Change-Id: Ibb3339315975caab0ac5b7734400e8e13602aa36
    
    This is an imported pull request from https://github.com/androidx/androidx/pull/623.
    
    Resolves #623
    Github-Pr-Head-Sha: d3c02acf14b52c95ee5155bf67705628764a4bd5
    GitOrigin-RevId: 8c9da2598f6d9dae6ba0a508aeb8e33b4e5ebf03
    Change-Id: I35474c1722141f23b74f4ed06e13357dbb1c7f80