Update git submodules
* Update frameworks/support from branch 'androidx-main'
  to 343414167c1ece1456644ff9a74c5386d6e5ef16
  - Merge "Shorter build_error.log" into androidx-main
  - Shorter build_error.log
    
    primarily to improve Gerrit previews
    
    - No longer splitting Gradle reproduction command into multiple lines
    - build_log_simplifier.py now stripping trailing blank lines
    - Removing some additional, specific messages that aren't needed
    
    Bug: 330373483
    
    Test: echo a | tee -a `find annotation/ -name "*.kt" && \
          ./busytown/androidx.sh` \
          # and see that it says this:
    
            ############################################################################
            Attempting to locate the relevant error messages via build_log_simplifier.py
            ############################################################################
    
            Detected these failing tasks: [':annotation:annotation:compileKotlinJvm']
            Calculating task graph as configuration cache cannot be reused because an input to unknown location has changed.
            > Task :annotation:annotation:compileKotlinJvm
            e: file://$SUPPORT/annotation/annotation/src/commonMain/kotlin/androidx/annotation/ReturnThis.kt:26:1 Expecting a top level declaration
    
            > Task :camera:integration-tests:camera-testapp-uiwidgets:mergeReleaseResources UP-TO-DATE
    
            Execution failed for task ':annotation:annotation:compileKotlinJvm'.
    
            * Exception is:
            org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':annotation:annotation:compileKotlinJvm'.
            Caused by: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
            Caused by: org.jetbrains.kotlin.gradle.tasks.CompilationErrorException: Compilation error. See log for more details
            	at org.jetbrains.kotlin.gradle.tasks.TasksUtilsKt.throwExceptionIfCompilationFailed(tasksUtils.kt:20)
    
            BUILD FAILED in 2m 36s
    
            Gradle command failed:
                ./gradlew --ci buildOnServer createAllArchives checkExternalLicenses listTaskOutputs exportSboms -Pandroidx.enableComposeCompilerMetrics=true -Pandroidx.enableComposeCompilerReports=true -Pandroidx.constraints=true --no-daemon --profile
    
    Change-Id: Icbb229e1e0ee0ce575869d37d874e79704f8398a