Update git submodules
* Update frameworks/support from branch 'androidx-main'
  to fd281798b8972ccf9cd87c2add18a071142cbe27
  - Merge "If project not found, try to print project subset in error message" into androidx-main
  - If project not found, try to print project subset in error message
    
    This adds a new resolveProject() method that prints the active project subset if a project is not found
    This also updates projectOrArtifact to use resolveProject()
    This also updates some other cases to use resolveProject()
    
    This doesn't help in the case of directly calling project() but it should these other cases at least
    
    Bug: 249808222
    Test: Make :room:room-paging dependOn :paging:paging-testing and make sure :paging-paging-testing is not in the COMPOSE project subset and run this:
    
              ANDROIDX_PROJECTS=COMPOSE ./gradlew projects --stacktrace -Pandroidx.summarizeStderr
    
          And see that it says this:
    
              Detected these failing tasks: []
              FAILURE: Build failed with an exception.
    
              * Where:
              Build file '$SUPPORT/room/room-paging/build.gradle' line: 36
    
              * What went wrong:
              A problem occurred evaluating project ':room:room-paging'.
              > Project :paging:paging-testing not found in subset COMPOSE
    
              * Exception is:
              org.gradle.api.GradleScriptException: A problem occurred evaluating project ':room:room-paging'.
              Caused by: org.gradle.api.UnknownProjectException: Project :paging:paging-testing not found in subset COMPOSE
              	at androidx.build.ProjectResolverKt.resolveProject(ProjectResolver.kt:32)
              	at androidx.build.AndroidXImplPlugin$registerProjectOrArtifact$1.invoke(AndroidXImplPlugin.kt:163)
              	at androidx.build.AndroidXImplPlugin$registerProjectOrArtifact$1.invoke(AndroidXImplPlugin.kt:158)
              	at build_1jj2lpfau9n7cfku2udvwylzb$_run_closure2.doCall($SUPPORT/room/room-paging/build.gradle:36)
              	at build_1jj2lpfau9n7cfku2udvwylzb.run($SUPPORT/room/room-paging/build.gradle:35)
              Caused by: org.gradle.api.UnknownProjectException: Project with path ':paging:paging-testing' could not be found in project ':room:room-paging'.
              	at androidx.build.ProjectResolverKt.resolveProject(ProjectResolver.kt:24)
    
    Test: Treehugger runs busytown/*.sh
    
    Change-Id: Ice02cf2d85101df957391a239afc415147f0b5a2