Update git submodules
* Update frameworks/support from branch 'androidx-main'
  to f83f254b237e3a869a8b7df9297ecda3f1008684
  - Merge "Add AGP 9.2.0-alpha05 and Gradle 9.5.0-milestone7" into androidx-main
  - Merge "Revert "Fix factory resolution for plain owners"" into androidx-main
  - Add AGP 9.2.0-alpha05 and Gradle 9.5.0-milestone7
    
    AGP requires gradle to be 9.5.0-milestone5 to work
    
    For the change in buildSrc/kotlin-dsl-dependency.gradle:
    Gradle has split the gradle-kotlin-dsl dependency in Gradle 9.5.0 into multiple jars (e.g., gradle-kotlin-dsl-shared-runtime.jar, etc.)
    
    The previous implementation of findGradleKotlinDsl() only fetched the main gradle-kotlin-dsl-<version>.jar. Because of this, the classes contained within the other gradle-kotlin-dsl jars (like org.gradle.kotlin.dsl.internal.sharedruntime.codegen.PluginEntryCache) were missing, resulting in `java.lang.NoClassDefFoundError` for the `:buildSrc-tests:test` task when upgrading to Gradle 9.5.0-milestone7
    
    BUG: 495460240
    TESTED: CI
    Change-Id: Ibe7994cacc1300961838b9c3e98883234b0cce7e
    
  - Revert "Fix factory resolution for plain owners"
    
    This reverts commit d0325d01dd1805c3c74251c2942880a0988b8ad2.
    
    Reason for revert: original issue fixed in aosp/4006233
    
    Change-Id: I5f7b435c34438231e5a38c72f878ac33670db1e6
    

* Update prebuilts/androidx/external from branch 'androidx-main'
  to a3c6e9dc1e4127191d5fc66e7d29f59e651dc6b0
  - Merge "Add AGP 9.2.0-alpha05 prebuilts" into androidx-main
  - Add AGP 9.2.0-alpha05 prebuilts
    
    Change-Id: I595c218ac8377f7e7f54a71beb5c64a3249c33e5
    

* Update tools/external/gradle from branch 'androidx-main'
  to a7f285a800314b464fe1b62af10c06276f8fe841
  - Merge "Add gradle-9.5.0-milestone7 prebuilts" into androidx-main
  - Add gradle-9.5.0-milestone7 prebuilts
    
    Change-Id: Ia23bf7453dab924233b10c8631f6ed1fd46b9094