Update git submodules
* Update frameworks/support from branch 'androidx-main'
  to 7f499f4ed0408de8550f381adcd719fa74c9759d
  - Merge changes I51581522,I2dd3c244 into androidx-main
    
    * changes:
      Fix IllegalStateException from camera updates after shutdown
      Fix flaky Camera2DeviceSurfaceManagerTest
    
  - Fix IllegalStateException from camera updates after shutdown
    
    An IllegalStateException can occur if a camera availability update
    is processed after the CameraPipe instance has been shut down.
    
    This leads to a crash with the following stack trace:
    ```
    java.lang.IllegalStateException: Check failed.
    	at androidx.camera.camera2.pipe.CameraPipeImpl.cameras(CameraPipe.kt:316)
    	...
    	at androidx.camera.core.impl.CameraPresenceProvider$SourceObservableObserver.onNewData(CameraPresenseProvider.kt:112)
    ```
    
    There was a race condition in PipeCameraPresenceSource. The underlying
    camera ID Flow could emit a new list of cameras after stopMonitoring()
    had been called. This late update would propagate to listeners,
    eventually causing a call to a CameraPipe instance that was already
    shut down, triggering the IllegalStateException.
    
    This CL introduces an isMonitoring AtomicBoolean flag to
    PipeCameraPresenceSource to make it robust against this
    race condition. The startMonitoring() and stopMonitoring() methods are
    now idempotent, preventing issues from redundant calls.
    
    Bug: 433987353
    Test: SupportedQualitiesVerificationTest
    Change-Id: I51581522e96ddabfa878526532f825b78bf95fcc
    
  - Fix flaky Camera2DeviceSurfaceManagerTest
    
    The Camera2DeviceSurfaceManagerTest is flaky because
    of a race condition.
    
    The test adds fake cameras using shadowCameraManager and
    expects to receive specific camera updates. However, the
    shadowCameraManager can also trigger its own camera
    availability callbacks, which interferes with the test's
    assertions.
    
    This change makes the test more stable by removing some of
    the verification logic that was sensitive to this race
    condition. The updated test is less strict about the number
    of callbacks received, which resolves the flakiness.
    
    Bug: 434199701
    Test: Camera2DeviceSurfaceManagerTest
    Change-Id: I2dd3c244f718c8e1c844be2851662ec8e29e3e8d