Update git submodules
* Update frameworks/support from branch 'androidx-main'
  to 4fd0e09aca282fbc7a6b6c7167e64d639bdca750
  - Merge "Fix room integration tests on API 17" into androidx-main
  - Fix room integration tests on API 17
    
    These tests started failing on API 17 after aosp/2093960 that upgraded
    espresso and AndroidJUnitRunner.
    
    java.lang.NoClassDefFoundError: androidx.tracing.Trace
    at androidx.test.runner.AndroidJUnitRunner.onCreate(AndroidJUnitRunner.java:291)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4382)
    ...
    
    This was because Trace class was no longer in the primary dex file.
    
    To fix it, use AGP API to specify that Trace class needs to be in the
    primary dex.
    https://developer.android.com/studio/build/multidex#multidexkeepfile-property
    
    Bug: 233671924
    Test: locally run these room tests on API 17 emulator
    Change-Id: I545e7185a5fe092508c7cb1601a241eeb2c1d819