Update git submodules
* Update frameworks/support from branch 'androidx-main'
  to 593662e6e020d8cff6a7745710ec1324d8951280
  - Merge changes Id2b52918,I4bbfff4b,Ibd56c95c,I6c55e9ad,I4d203977, ... into androidx-main
    
    * changes:
      Enabling maxDepVersions checking for all subprojects rather than just direct children
      Check that projectsMap is not modified after its first access
      More efficient maxDepVersions dependency substitution
      Remove unused isAtLeastR check
      Suppress some required deprecation usages that affect maxDepVersions
      Remove unused setting of mContext
    
  - Enabling maxDepVersions checking for all subprojects rather than just direct children
    
    Bug: 181247015
    Test: Run `./gradlew :appcompat:appcompat:assembleDebug -Pandroidx.useMaxDepVersions`, see that it fails:
    
      $SUPPORT/appcompat/appcompat/src/main/java/androidx/appcompat/widget/SuggestionsAdapter.java:776: error: mContext has private access in CursorAdapter
              return mContext.getContentResolver().query(uri, null, selection, selArgs, null);
    
    Test: git checkout HEAD^ && ./gradlew assembleDebug -Pandroidx.useMaxDepVersions # and see that it fails, saying that it is attempting to add a project to the map after it was accessed
    
    Change-Id: Id2b529188331ac15bdb61d7cd1e3a9c3a78762cf
    
  - Check that projectsMap is not modified after its first access
    
    This change fails on its own and is just a test for the following change
    
    Bug: 181247015
    
    Test: ./gradlew assembleDebug -Pandroidx.useMaxDepVersions # and see that it fails, saying that it is attempting to add a project to the map after it was accessed
    
    Change-Id: I4bbfff4bb74b6da30f02d63b69cd8a82ad46feba
    
  - More efficient maxDepVersions dependency substitution
    
    So that Gradle can handle it when we enable lots of these
    
    Bug: 181247015
    
    Test: Treehugger runs busytown/androidx_max_dep_versions.sh
    
    Change-Id: Ibd56c95c79640055795ff64c36a62c8ac6bb6cdf
    
  - Remove unused isAtLeastR check
    
    When using the latest BuildCompat, if SDK_INT == 29, then isAtLeastR is false
    
    Bug: 181247015
    Test: ./gradlew :test-screenshot:compileDebugKotlin -Pandroidx.useMaxDepVersions --ci
    Change-Id: I6c55e9adc3ede17e5cb5a01b09000897b63b40ae
    
  - Suppress some required deprecation usages that affect maxDepVersions
    
    Bug: 181247015
    Test: ./gradlew :internal-testutils-runtime:compileDebugKotlin -Pandroidx.useMaxDepVersions --ci
    Change-Id: I4d203977e9b6295628c8dbcdb2b92d8059e7b852
    
  - Remove unused setting of mContext
    
    it should already be set by the superclass
    
    Bug: 181247015
    Test: Treehugger should run tests
    
    Change-Id: I4dfc2372346a0858dce4e4bed996cc846c1833c8